name: flapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  audioplayers: ^6.4.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.0-dev.15
  riverpod_annotation: ^3.0.0-dev.15

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint:
  riverpod_generator: ^3.0.0-dev.15
  riverpod_lint: ^3.0.0-dev.15

flutter:
  uses-material-design: true
  assets:
    - assets/power01.ogg
